# Generated by Django 5.0.1 on 2024-03-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, related_name='cug', related_query_name='custom_user_group', to='auth.group', verbose_name='groups')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.notification')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='cup', related_query_name='custom_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
