# Generated by Django 5.0.1 on 2024-03-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_notification_groups_notification_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_permissions',
        ),
    ]
